name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
      - name: Checkout codecov-cli test branch
        uses: actions/checkout@v4
        with:
          repository: codecov/codecov-cli
          ref: 53289f820ca3f2c05994292aa77d179732d1ed5a
          submodules: 'true'
      - name: Run Codecov with test branch of CLI
        run: |
          pip install -r requirements.txt
          pip install .
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r api/requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov=api.calculator --cov-report=xml
      - name: Upload to Codecov
        run: |
          codecovcli -v upload-process
